### PR TITLE
Activate enableExternalSecretStores option

### LINKED ISSUE #100: Enable external secret store to publish secret to Vault
### What problem are you facing?

Using crossplane, we need to generate on demand some random_password (using hashicorp/random) and save them to the Vault, which will be used later by the kubernetes created at the same time (eg. by a CSI Driver).
We tried to build a "crossplane-provider-random" using provider-jet-template, but for some reason it didn't work as aspected, so we turned to provider-terraform which works fine for the generation part but for now we don't have the option to enable the [external secret store](https://github.com/crossplane/crossplane/pull/2940)

### How could Crossplane help solve your problem?

We need to modified a bit the code by enabling the flag --enable-external-secret-stores and the logic behind, a storeconfig type and its crd, the modfied version is now used in our project and works pretty well.

### PR DESCRIPTION
**Pull request by ZhengjunHUO**
Signed-off-by: ZhengjunHUO <firelouiszj@hotmail.com>

### Description of your changes

Fixes #100 

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

Cherry picked from PR #101 for [release-0.3](https://github.com/crossplane-contrib/provider-terraform/tree/release-0.3)

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Review by ytsarev — COMMENTED** [review]
That looks great, thanks a lot @ZhengjunHUO 

Is it possible to extend the documentation(README) with the brief documentation of ExternalSecretStore support?

**Comment by ZhengjunHUO** [comment]
@ytsarev sure thing, you're right, it could be helpful for those who are interested.

**Review by ytsarev — APPROVED** [review]
This looks great, thanks a lot @ZhengjunHUO!

**Comment by jeanduplessis** [comment]
@ZhengjunHUO I hope you’re doing well! My name is Jean and I’m an Engineering Manager at Upbound. As Upbound, we’re preparing to add `crossplane-contrib/provider-terraform` to our Official Provider program, which will make it part of the providers Upbound officially supports and maintains. The goal of this program is to help converge the Crossplane community’s efforts around a single set of high-quality providers. This will reduce confusion around what provider to use and accelerate project adoption. It will continue to be open source under the Apache 2.0 license, similar to the current provider but will live under the Upbound organization in GitHub and requires contributors to sign a CLA for contributions. You have some commits in `crossplane-contrib/provider-terraform`, including this PR, which we appreciate and would like to include in the `upbound/provider-terraform` official provider, too, so I’d like to ask you to [sign the CLA here](https://cla.upbound.io/upbound/provider-terraform) so we can include your contribution in the official provider. We’d also love for you to continue to contribute to the provider in its new home in the upbound org on GitHub to help us to continue supporting the community. Let me know if you have any further questions.

**Comment by ZhengjunHUO** [comment]
@jeanduplessis it's done, it's always a pleasure to contribute to the community.

**Comment by jeanduplessis** [comment]
Thank you @ZhengjunHUO 🙏🏻

**Pull request merged**
