### PR TITLE
Injected identity

### LINKED ISSUE #70: Does not seem to work with IAM roles for service accounts
### What happened?

Get the following error:

```
 Warning  CannotObserveExternalResource  6s (x7 over 103s)     managed/workspace.tf.crossplane.io  cannot diff (i.e. plan) Terraform configuration: error configuring terraform aws provider: no valid credential sources for terraform aws provider found.
```

### How can we reproduce it?

Set the controller config to the following:
```
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: terraform-config
  labels:
    app: crossplane-provider-terraform
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<account>:role/<rolename>
spec:
  podSecurityContext:
    fsGroup: 2000
  image: crossplane/provider-terraform-controller:v0.2.0
  args: ["-d"]
```
Can see the annotation however the terraform aws provider does not seem to use it

### What environment did it happen in?
Crossplane version: 
1.8

### PR DESCRIPTION
**Pull request by luisdavim**
### Description of your changes

* Adding some documentation and an example regarding how to setup the provider using AWS IRSA.
* Fix a bug where `InjectedIdentity` was wrongly advertised as a valid credentials source for the provider config.
* Added an extra commit with some linter fixes to the README, I can revert it if you don't agree with my linter setup...

Fixes #70 

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

I have manually tested the setup in a real EKS cluster.

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

**Review by ytsarev — CHANGES_REQUESTED** [review]
Thanks a lot for the contribution! Let's agree and fix Markdown style changes in a separate issue, please revert the unrelated changes

**Comment by luisdavim** [comment]
These were automatically done by my IDE. I'll revert them.

**Comment by luisdavim** [comment]
Done, I've reverted the commit with the linter changes, should I open a separate PR for that?

**Review by ytsarev — APPROVED** [review]
@luisdavim thanks a lot for the great contribution!

**Pull request merged**
